# Project-wide Gradle settings.

# Enable AndroidX support
android.useAndroidX=true

# Enable non-transitive R class for faster builds
android.nonTransitiveRClass=true

# Kotlin code style
kotlin.code.style=official

# Enable KSP incremental compilation
ksp.incremental=true

# JVM Arguments for Gradle daemon
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
